%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record(payment, {anyAttribs :: anyAttribs(),
	self :: string() | undefined,
	'merchant-account-id' :: 'merchant-account-id'() | undefined,
	'merchant-account-resolver-category' :: string() | undefined,
	'transaction-id' :: string() | undefined,
	'request-id' :: string() | undefined,
	'transaction-type' :: string() | undefined,
	'transaction-state' :: string() | undefined,
	'completion-time-stamp' :: string() | undefined,
	statuses :: statuses() | undefined,
	'avs-code' :: string() | undefined,
	'csc-code' :: string() | undefined,
	'requested-amount' :: money() | undefined,
	'parent-transaction-id' :: string() | undefined,
	'group-transaction-id' :: string() | undefined,
	'account-holder' :: 'account-holder'() | undefined,
	'account-holder-requested-amount' :: money() | undefined,
	'account-holder-conversion-rate' :: string() | undefined,
	shipping :: shipping() | undefined,
	'loyalty-card' :: 'loyalty-card'() | undefined,
	card :: card() | undefined,
	'card-token' :: 'card-token'() | undefined,
	cryptogram :: cryptogram() | undefined,
	'ip-address' :: string() | undefined,
	'order-number' :: string() | undefined,
	'order-detail' :: string() | undefined,
	'order-items' :: 'order-items'() | undefined,
	descriptor :: string() | undefined,
	notifications :: notifications() | undefined,
	'custom-fields' :: 'custom-fields'() | undefined,
	'payment-methods' :: 'payment-methods'() | undefined,
	'acquirer-reference-number' :: string() | undefined,
	'chargeback-id' :: string() | undefined,
	'chargeback-date' :: string() | undefined,
	'chargeback-retrieval-date' :: string() | undefined,
	'parent-transaction-amount' :: money() | undefined,
	'chargeback-conversion-rate' :: string() | undefined,
	'chargeback-reason-code' :: string() | undefined,
	'chargeback-provider-transaction-id' :: string() | undefined,
	'chargeback-provider-account-id' :: string() | undefined,
	'chargeback-provider-id' :: string() | undefined,
	'chargeback-additional-info' :: string() | undefined,
	'authorization-code' :: string() | undefined,
	'three-d' :: 'three-d'() | undefined,
	'airline-industry' :: 'airline-industry'() | undefined,
	'cruise-industry' :: 'cruise-industry'() | undefined,
	'bank-account' :: 'bank-account'() | undefined,
	'merchant-bank-account' :: 'bank-account'() | undefined,
	mandate :: mandate() | undefined,
	'creditor-id' :: string() | undefined,
	'consumer-id' :: string() | undefined,
	'api-id' :: string() | undefined,
	'api-transaction-id' :: string() | undefined,
	'redirect-url' :: string() | undefined,
	'processing-redirect-url' :: string() | undefined,
	'cancel-redirect-url' :: string() | undefined,
	'fail-redirect-url' :: string() | undefined,
	'success-redirect-url' :: string() | undefined,
	locale :: string() | undefined,
	'psp-name' :: string() | undefined,
	'custom-css-url' :: string() | undefined,
	'due-date' :: string() | undefined,
	'capture-date' :: string() | undefined,
	'expiration-date' :: string() | undefined,
	files :: files() | undefined,
	invoice :: invoice() | undefined,
	'entry-mode' :: string() | undefined,
	periodic :: periodic() | undefined,
	wallet :: wallet() | undefined,
	country :: string() | undefined,
	settlement :: settlement() | undefined,
	batch :: batch() | undefined,
	consumer :: consumer() | undefined,
	'provider-transaction-reference-id' :: string() | undefined,
	'risk-reference-id' :: string() | undefined,
	'card-bin-id' :: string() | undefined,
	device :: device() | undefined,
	pos :: pos() | undefined,
	iso :: iso() | undefined,
	'iso-recon' :: 'iso-recon'() | undefined,
	'voucher-id' :: string() | undefined,
	voucher :: voucher() | undefined,
	'instrument-country' :: string() | undefined,
	'request-type' :: string() | undefined,
	'merchant-origin-url' :: string() | undefined,
	'customer-id' :: string() | undefined,
	signature :: signature() | undefined,
	'sub-merchant-info' :: 'sub-merchant-info'() | undefined,
	'one-time-password' :: string() | undefined,
	browser :: browser() | undefined,
	'additional-merchant-data' :: string() | undefined,
	b2b :: boolean() | undefined}).

-type payment() :: #payment{}.


-record(signature, {anyAttribs :: anyAttribs(),
	'signature-type' :: string() | undefined,
	'signature-value' :: string() | undefined,
	'signature-encoding' :: string() | undefined}).

-type signature() :: #signature{}.


-record(voucher, {anyAttribs :: anyAttribs(),
	'voucher-code' :: string() | undefined,
	'voucher-brand-id' :: string() | undefined,
	'voucher-token-id' :: string() | undefined,
	'voucher-description' :: string() | undefined}).

-type voucher() :: #voucher{}.


-record(device, {anyAttribs :: anyAttribs(),
	fingerprint :: string() | undefined,
	'policy-score' :: integer() | undefined}).

-type device() :: #device{}.


-record('iso-recon', {anyAttribs :: anyAttribs(),
	'captured-sale-count' :: string() | undefined,
	'captured-sale-amount' :: string() | undefined,
	'captured-refund-count' :: string() | undefined,
	'captured-refund-amount' :: string() | undefined,
	'authorized-sale-count' :: string() | undefined,
	'authorized-sale-amount' :: string() | undefined,
	'authorized-refund-count' :: string() | undefined,
	'authorized-refund-amount' :: string() | undefined,
	'response-text' :: string() | undefined,
	'number-of-reversal' :: string() | undefined,
	'number-of-adjustment' :: string() | undefined,
	'number-of-roc' :: string() | undefined}).

-type 'iso-recon'() :: #'iso-recon'{}.


-record(iso, {anyAttribs :: anyAttribs(),
	'merchant-id' :: string() | undefined,
	'terminal-id' :: string() | undefined,
	'bank-terminal-id' :: string() | undefined,
	'response-code' :: string() | undefined,
	'approval-code' :: string() | undefined,
	'retrieval-reference-number' :: string() | undefined,
	'invoice-number' :: string() | undefined,
	'transaction-advise-ref' :: string() | undefined,
	'transaction-reversal-ref' :: string() | undefined,
	'transaction-amount' :: string() | undefined,
	'message-type-id' :: string() | undefined,
	'processing-code' :: string() | undefined,
	'system-trace-number' :: string() | undefined,
	'pos-transaction-time' :: string() | undefined,
	'pos-transaction-date' :: string() | undefined,
	'pos-entry-mode' :: string() | undefined,
	'pos-pin-input-length-capability' :: integer() | undefined,
	'card-seq-number' :: string() | undefined,
	'pos-nii' :: string() | undefined,
	'pos-condition-code' :: string() | undefined,
	'additional-amount' :: string() | undefined,
	'request-emv-icc-data' :: string() | undefined,
	'response-emv-icc-data' :: string() | undefined,
	'batch-number' :: string() | undefined,
	'original-amount' :: string() | undefined,
	'original-message-data' :: string() | undefined,
	'settle-id' :: string() | undefined,
	'settle-on' :: string() | undefined,
	'pin-data' :: string() | undefined,
	'product-code' :: string() | undefined,
	'msg-auth-code' :: string() | undefined,
	'iso-fields' :: 'iso-fields'() | undefined}).

-type iso() :: #iso{}.


-record('iso-fields', {anyAttribs :: anyAttribs(),
	'iso-field' :: ['iso-field'()] | undefined}).

-type 'iso-fields'() :: #'iso-fields'{}.


-record('iso-field', {anyAttribs :: anyAttribs(),
	'field-name' :: string(),
	'field-value' :: string(),
	'#text' :: string() | undefined}).

-type 'iso-field'() :: #'iso-field'{}.


-record('sub-merchant-info', {anyAttribs :: anyAttribs(),
	id :: string() | undefined,
	name :: string() | undefined,
	street :: string() | undefined,
	city :: string() | undefined,
	'postal-code' :: string() | undefined,
	state :: string() | undefined,
	country :: string() | undefined,
	category :: string() | undefined}).

-type 'sub-merchant-info'() :: #'sub-merchant-info'{}.


-record('order-items', {anyAttribs :: anyAttribs(),
	'order-item' :: ['order-item'()]}).

-type 'order-items'() :: #'order-items'{}.


-record('order-item', {anyAttribs :: anyAttribs(),
	name :: string(),
	description :: string() | undefined,
	'article-number' :: string() | undefined,
	amount :: money(),
	'tax-amount' :: money() | undefined,
	'tax-rate' :: string() | undefined,
	quantity :: string(),
	type :: string() | undefined,
	discount :: string() | undefined}).

-type 'order-item'() :: #'order-item'{}.


-record(pos, {anyAttribs :: anyAttribs(),
	'merchant-id' :: string() | undefined,
	'terminal-id' :: string() | undefined}).

-type pos() :: #pos{}.


-record(batch, {anyAttribs :: anyAttribs(),
	'file-name' :: string() | undefined,
	'record-number' :: string() | undefined}).

-type batch() :: #batch{}.


-record(settlement, {anyAttribs :: anyAttribs(),
	'gross-amount' :: string(),
	currency :: string()}).

-type settlement() :: #settlement{}.


-record(wallet, {anyAttribs :: anyAttribs(),
	'account-id' :: string(),
	'merchant-id' :: string() | undefined,
	'request-token' :: string() | undefined,
	'pair-token' :: string() | undefined,
	'card-id' :: string() | undefined,
	'address-id' :: string() | undefined,
	'provider-ref' :: string() | undefined,
	'provider-transaction-id' :: string() | undefined,
	'wallet-data' :: string() | undefined}).

-type wallet() :: #wallet{}.


-record(periodic, {anyAttribs :: anyAttribs(),
	'periodic-type' :: string(),
	'sequence-type' :: string() | undefined,
	'number-of-installments' :: string() | undefined,
	'recurring-expire-date' :: string() | undefined}).

-type periodic() :: #periodic{}.


-record(file, {anyAttribs :: anyAttribs(),
	content :: string() | undefined,
	'type-id' :: string() | undefined,
	name :: string() | undefined}).

-type file() :: #file{}.


-record(files, {anyAttribs :: anyAttribs(),
	file :: [file()] | undefined}).

-type files() :: #files{}.


-record(invoice, {anyAttribs :: anyAttribs(),
	'invoice-number' :: string() | undefined,
	'invoice-date' :: string() | undefined,
	'delivery-method' :: string() | undefined}).

-type invoice() :: #invoice{}.


-record(mandate, {anyAttribs :: anyAttribs(),
	'mandate-id' :: string() | undefined,
	'signed-date' :: string() | undefined,
	'signed-city' :: string() | undefined,
	'signature-image' :: string() | undefined}).

-type mandate() :: #mandate{}.


-record('bank-account', {anyAttribs :: anyAttribs(),
	'bank-name' :: string() | undefined,
	'branch-city' :: string() | undefined,
	'branch-state' :: string() | undefined,
	'branch-address' :: string() | undefined,
	iban :: string() | undefined,
	bic :: string() | undefined,
	'account-number' :: string() | undefined,
	'bank-code' :: string() | undefined}).

-type 'bank-account'() :: #'bank-account'{}.


-record('cruise-industry', {anyAttribs :: anyAttribs(),
	'carrier-code' :: string(),
	'agent-code' :: string() | undefined,
	'travel-package-type-code' :: string() | undefined,
	'ticket-number' :: string() | undefined,
	'passenger-name' :: string() | undefined,
	'lodging-check-in-date' :: string() | undefined,
	'lodging-check-out-date' :: string() | undefined,
	'lodging-room-rate' :: money() | undefined,
	'number-of-nights' :: string() | undefined,
	'lodging-name' :: string() | undefined,
	'lodging-city-name' :: string() | undefined,
	'lodging-region-code' :: string() | undefined,
	'lodging-country-code' :: string() | undefined,
	itinerary :: itinerary() | undefined}).

-type 'cruise-industry'() :: #'cruise-industry'{}.


-record('airline-industry', {anyAttribs :: anyAttribs(),
	'airline-code' :: string(),
	'airline-name' :: string() | undefined,
	'passenger-code' :: string() | undefined,
	'passenger-name' :: string() | undefined,
	'passenger-phone' :: string() | undefined,
	'passenger-email' :: string() | undefined,
	'passenger-ip-address' :: string() | undefined,
	'ticket-issue-date' :: string() | undefined,
	'ticket-number' :: string(),
	'ticket-restricted-flag' :: string() | undefined,
	'pnr-file-key' :: string() | undefined,
	'ticket-check-digit' :: string() | undefined,
	'agent-code' :: string() | undefined,
	'agent-name' :: string() | undefined,
	'non-taxable-net-amount' :: money() | undefined,
	'ticket-issuer' :: 'ticket-issuer'() | undefined,
	'number-of-passengers' :: string() | undefined,
	'reservation-code' :: string() | undefined,
	itinerary :: itinerary() | undefined}).

-type 'airline-industry'() :: #'airline-industry'{}.


-record(itinerary, {anyAttribs :: anyAttribs(),
	segment :: [segment()]}).

-type itinerary() :: #itinerary{}.


-record(segment, {anyAttribs :: anyAttribs(),
	'carrier-code' :: string(),
	'departure-airport-code' :: string(),
	'departure-city-code' :: string(),
	'arrival-airport-code' :: string(),
	'arrival-city-code' :: string(),
	'departure-date' :: string(),
	'arrival-date' :: string(),
	'flight-number' :: string() | undefined,
	'fare-class' :: string() | undefined,
	'fare-basis' :: string() | undefined,
	'stop-over-code' :: string() | undefined,
	'tax-amount' :: money() | undefined}).

-type segment() :: #segment{}.


-record(browser, {anyAttribs :: anyAttribs(),
	accept :: string() | undefined,
	'user-agent' :: string() | undefined,
	'ip-address' :: string() | undefined,
	hostname :: string() | undefined,
	'browser-version' :: string() | undefined,
	os :: string() | undefined,
	'screen-resolution' :: string() | undefined,
	referrer :: string() | undefined}).

-type browser() :: #browser{}.


-record('ticket-issuer', {anyAttribs :: anyAttribs(),
	address :: address() | undefined}).

-type 'ticket-issuer'() :: #'ticket-issuer'{}.


-record('three-d', {anyAttribs :: anyAttribs(),
	pares :: string() | undefined,
	eci :: string() | undefined,
	xid :: string() | undefined,
	'cardholder-authentication-value' :: string() | undefined,
	pareq :: string() | undefined,
	'acs-url' :: string() | undefined,
	'attempt-three-d' :: boolean() | undefined,
	'liability-shift-indicator' :: string() | undefined,
	'cardholder-authentication-status' :: string() | undefined}).

-type 'three-d'() :: #'three-d'{}.


-record(statuses, {anyAttribs :: anyAttribs(),
	status :: [status()]}).

-type statuses() :: #statuses{}.


-record(status, {anyAttribs :: anyAttribs(),
	code :: string(),
	description :: string(),
	severity :: string(),
	'provider-transaction-id' :: string() | undefined,
	'provider-code' :: string() | undefined,
	'provider-message' :: string() | undefined,
	field :: string() | undefined,
	detail :: string() | undefined,
	'#text' :: string() | undefined}).

-type status() :: #status{}.


-record('payment-methods', {anyAttribs :: anyAttribs(),
	'payment-method' :: ['payment-method'()] | undefined}).

-type 'payment-methods'() :: #'payment-methods'{}.


-record('payment-method', {anyAttribs :: anyAttribs(),
	url :: string() | undefined,
	name :: string(),
	'card-types' :: 'card-types'() | undefined}).

-type 'payment-method'() :: #'payment-method'{}.


-record('card-types', {anyAttribs :: anyAttribs(),
	'card-type' :: [string()] | undefined}).

-type 'card-types'() :: #'card-types'{}.


-record('custom-fields', {anyAttribs :: anyAttribs(),
	'custom-field' :: ['custom-field'()] | undefined}).

-type 'custom-fields'() :: #'custom-fields'{}.


-record('custom-field', {anyAttribs :: anyAttribs(),
	'field-name' :: string(),
	'field-value' :: string(),
	'#text' :: string() | undefined}).

-type 'custom-field'() :: #'custom-field'{}.


-record(notifications, {anyAttribs :: anyAttribs(),
	format :: string() | undefined,
	notification :: [notification()] | undefined}).

-type notifications() :: #notifications{}.


-record(notification, {anyAttribs :: anyAttribs(),
	'transaction-state' :: string() | undefined,
	url :: string(),
	'#text' :: string() | undefined}).

-type notification() :: #notification{}.


-record(cryptogram, {anyAttribs :: anyAttribs(),
	'cryptogram-type' :: string(),
	'cryptogram-value' :: string() | undefined}).

-type cryptogram() :: #cryptogram{}.


-record('card-token', {anyAttribs :: anyAttribs(),
	'token-id' :: string() | undefined,
	'token-ext-id' :: string() | undefined,
	'masked-account-number' :: string() | undefined}).

-type 'card-token'() :: #'card-token'{}.


-record('encryption-context', {anyAttribs :: anyAttribs(),
	value :: string() | undefined,
	version :: string() | undefined,
	algorithm :: string() | undefined,
	parameter :: string() | undefined,
	padding :: string() | undefined}).

-type 'encryption-context'() :: #'encryption-context'{}.


-record('card-raw', {anyAttribs :: anyAttribs(),
	data :: string() | undefined,
	encoding :: string() | undefined,
	format :: string() | undefined,
	'encryption-context' :: 'encryption-context'() | undefined,
	'encryption-version' :: string() | undefined}).

-type 'card-raw'() :: #'card-raw'{}.


-record('card-pin', {anyAttribs :: anyAttribs(),
	data :: string() | undefined,
	encoding :: string() | undefined,
	format :: string() | undefined,
	'encryption-context' :: 'encryption-context'() | undefined,
	'encryption-version' :: string() | undefined}).

-type 'card-pin'() :: #'card-pin'{}.


-record('card-emv', {anyAttribs :: anyAttribs(),
	'request-icc-data' :: string() | undefined,
	'request-icc-data-encoding' :: string() | undefined,
	'response-icc-data' :: string() | undefined,
	'response-icc-data-encoding' :: string() | undefined}).

-type 'card-emv'() :: #'card-emv'{}.


-record(card, {anyAttribs :: anyAttribs(),
	'account-number' :: string() | undefined,
	'expiration-month' :: string() | nil,
	'expiration-year' :: string() | nil,
	'card-security-code' :: string() | undefined,
	'card-type' :: string(),
	'card-last-four' :: string() | undefined,
	'track-1' :: string() | undefined,
	'track-2' :: string() | undefined,
	'pin-data' :: string() | undefined,
	'card-emv' :: 'card-emv'() | undefined,
	'card-pin' :: 'card-pin'() | undefined,
	'card-raw' :: 'card-raw'() | undefined}).

-type card() :: #card{}.


-record('loyalty-card', {anyAttribs :: anyAttribs(),
	'account-number' :: string() | undefined,
	'personal-identification-number' :: string() | undefined,
	'promotion-code' :: string() | undefined,
	'activity-date' :: string() | undefined}).

-type 'loyalty-card'() :: #'loyalty-card'{}.


-record(shipping, {anyAttribs :: anyAttribs(),
	'first-name' :: string(),
	'last-name' :: string(),
	phone :: string() | undefined,
	address :: address(),
	email :: string() | undefined,
	'shipping-method' :: string() | undefined,
	'tracking-number' :: string() | undefined,
	'tracking-url' :: string() | undefined,
	'shipping-company' :: string() | undefined,
	'return-tracking-number' :: string() | undefined,
	'return-tracking-url' :: string() | undefined,
	'return-shipping-company' :: string() | undefined}).

-type shipping() :: #shipping{}.


-record(consumer, {anyAttribs :: anyAttribs(),
	'first-name' :: string(),
	'last-name' :: string(),
	email :: string() | undefined,
	gender :: string() | undefined,
	'date-of-birth' :: string() | undefined,
	phone :: string() | undefined,
	address :: address() | undefined,
	'merchant-crm-id' :: string() | undefined,
	'social-security-number' :: string() | undefined}).

-type consumer() :: #consumer{}.


-record('account-holder', {anyAttribs :: anyAttribs(),
	'first-name' :: string(),
	'last-name' :: string(),
	email :: string() | undefined,
	gender :: string() | undefined,
	'date-of-birth' :: string() | undefined,
	phone :: string() | undefined,
	address :: address() | undefined,
	'merchant-crm-id' :: string() | undefined,
	'social-security-number' :: string() | undefined}).

-type 'account-holder'() :: #'account-holder'{}.


-record(address, {anyAttribs :: anyAttribs(),
	'block-no' :: string() | undefined,
	level :: string() | undefined,
	unit :: string() | undefined,
	street1 :: string(),
	street2 :: string() | undefined,
	city :: string(),
	state :: string() | undefined,
	country :: string(),
	'postal-code' :: string() | undefined,
	'house-extension' :: string() | undefined}).

-type address() :: #address{}.


-record(money, {anyAttribs :: anyAttribs(),
	currency :: string(),
	'#text' :: string() | undefined}).

-type money() :: #money{}.


-record('merchant-account-id', {anyAttribs :: anyAttribs(),
	ref :: string() | undefined,
	'#text' :: string() | undefined}).

-type 'merchant-account-id'() :: #'merchant-account-id'{}.